### ISSUE TITLE
Meta: Fix all TypeScript build errors (2,544 total)

### ISSUE THREAD

**Issue by mikkihugo** [mikkihugo/claude-code-zen#182]
## Overview
This is a tracking issue for fixing all TypeScript build errors in the project. The project currently has 2,544 compilation errors preventing a clean build.

## Related Issues
- #176 - Fix TypeScript build errors in coordination/swarm/core (1,203 errors)
- #177 - Fix TypeScript build errors in knowledge domain (1,091 errors)
- #178 - Fix TypeScript build errors in neural/core (342 errors)
- #179 - Fix remaining TypeScript errors in smaller domains
- #181 - Address ESLint warnings (3,672 warnings)

## Strategy
1. Fix domains that other domains depend on first (types, utils, core)
2. Fix large error count domains (swarm/core, knowledge)
3. Fix remaining domains
4. Address ESLint warnings for code quality

## Success Metrics
- [ ] npm run build completes without errors
- [ ] All tests pass
- [ ] No regression in functionality
- [ ] Clean CI/CD pipeline

## Notes
- Some domains (core, utils, types, config, memory) already compile successfully when built independently
- The errors are primarily due to interdependencies and missing type exports
- Focus on fixing root causes rather than using 'any' as a workaround
